---
- name: Create Redis dir's
  file:
   path: "{{ item }}"
   state: directory
   mode: 0755
  with_items:
    - "{{ redis_conf_dir }}"
    - "{{ redis_run_dir }}"
    - "{{ redis_lib_dir }}"
  become: true

- name: Create Redis LOG DIR
  file:
   path: "{{ item }}"
   state: touch
   mode: 0755
  with_items:
    - "{{ redis_logfile }}"
    - "{{ sentinel_logfile }}"
  become: true

- name: Overcommit_memory warnings Fix
  lineinfile:
    dest: "/etc/sysctl.conf"
    line: "vm.overcommit_memory = 1"
  become: true

# Fix Transparent Huge Pages warnings
- name: Transparent Huge Pages Fix
  replace:
    dest: /sys/kernel/mm/transparent_hugepage/enabled
    regexp: '[always] madvise never'
    replace: 'never'
  become: true
  ignore_errors: True

- name: download redis
  get_url:
    url: "{{ redis_url }}"
    dest: "{{ install_dir }}"

- name: extract redis tarball
  unarchive:
    src: "{{ install_dir }}/redis-{{ redis_version }}.tar.gz"
    dest: "{{ install_dir }}"

- name: Run 'make install' target as root
  command: make -C "{{ redis_dir }}/src/"


- name: copy redis-server to /usr/local/bin/
  copy:
    src: "{{ redis_dir }}/src/redis-server"
    dest: /usr/local/bin/
    mode: 0755
    remote_src: yes
  become: true
  ignore_errors: True

- name: copy redis-cli to /usr/local/bin/
  copy:
    src: "{{ redis_dir }}/src/redis-cli"
    dest: /usr/local/bin/
    remote_src: yes
    mode: 0755
  become: true
  ignore_errors: True
