---
 #COPY MASTER CONF
- name: Copy Redis template
  copy:
    src: "roles/ansible-redis/templates/defaults/redis.conf"
    dest: "/etc/redis/redis.conf"
    mode: 0644
  become: true
  when: redis_role != "sentinel"

 #COPY SENTINEL CONF
- name: Copy Sentinel template
  copy:
    src: "roles/ansible-redis/templates/defaults/sentinel"
    dest: "/etc/redis/sentinel.conf"
    mode: 0644
  become: true
